{{ with .Values.storage.influxdb }}
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/name: influxdb
spec:
  {{ if hasKey . "externalAccess" }}
  {{ with .externalAccess }}
  type: {{ .type | default "ClusterIP" }}
  {{ if and (eq .type "LoadBalancer") .loadBalancerIP }}
  type: LoadBalancer
  loadBalancerIP: {{ .externalAccess.service.loadBalancerIP }}
  {{ end }}
  {{ end }}
  {{ end }}
  ports:
    - name: http-api
      port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app.kubernetes.io/name: influxdb
{{ end }}