apiVersion: v1
kind: Service
spec:
  ports:
  - name: incbmpsess
    #nodePort: {{ .Values.collectors.gobmp.ports.incomingBMPSessions }}
    port: {{ .Values.collectors.gobmp.ports.incomingBMPSessions }}
    protocol: TCP
    targetPort: 5000
  - name: perfmon
    #nodePort: {{ .Values.collectors.gobmp.ports.performanceMonitoring }}
    port: {{ .Values.collectors.gobmp.ports.performanceMonitoring }}
    protocol: TCP
    targetPort: 56767
  selector:
    app: "{{ .Values.collectors.gobmp.name }}"
  type: LoadBalancer
  loadBalancerIP: {{ .Values.collectors.gobmp.service.loadBalancerIP }}
metadata:
  name: "{{ .Values.collectors.gobmp.name }}"
  annotations:
    {{- if .Values.collectors.gobmp.service.annotations }}
    {{- toYaml .Values.collectors.gobmp.service.annotations | nindent 4 }}
    {{- end }}
