apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "{{- $replicas := int .Values.messaging.kafka.replicas}}{{- range $i, $e := until $replicas }}{{- if $i }},{{ end }}{{ $i }}@kafka-{{ $i }}.kafka-headless:9093{{- end }}"
  KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"