apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:  
      app.kubernetes.io/name: influxdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
    spec:
      containers:
        - name: influxdb
          image: {{ .Values.storage.influxdb.image }}
          ports:
            - name: http-api
              containerPort: 8086
              protocol: TCP
          envFrom:
            - configMapRef:
                name: influxdb-config
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-pvc