{{ with .Values.messaging.kafka }}
  {{ if hasKey . "externalAccess" }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  labels:
    app.kubernetes.io/name: kafka
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .externalAccess.loadBalancerIP }}
  ports:
    - name: kafka-external
      port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    app.kubernetes.io/name: kafka
{{ end }}
{{ end }}
