{{- with .Values.messaging.kafka }}
{{ if hasKey . "externalAccess" }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  labels:
    app.kubernetes.io/name: kafka
spec:
  type: {{ if .externalAccess }}{{ default "NodePort" .externalAccess.type }}{{ else }}ClusterIP{{ end }}
  {{- if and .externalAccess (eq .externalAccess.type "LoadBalancer") .externalAccess.loadBalancerIP }}
  loadBalancerIP: {{ .externalAccess.loadBalancerIP }}
  {{- end }}
  ports:
    - name: kafka-external
      port: 9094
      targetPort: 9094
      protocol: TCP
      {{- if and .externalAccess (eq .externalAccess.type "NodePort") .externalAccess.nodePort }}
      nodePort: {{ .externalAccess.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: kafka
{{ end }}
{{ end }}
