apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app.kubernetes.io/name: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: kafka-broker 
      targetPort: 9092
    - port: 9093
      name: kafka-control
      targetPort: 9093
  selector:
    app.kubernetes.io/name: kafka
  type: ClusterIP
  publishNotReadyAddresses: true